name: weather_forecast
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  dartz: ^0.10.1
  extended_image: ^8.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  http: ^1.1.0
  shared_preferences: ^2.2.2
  blur: ^3.1.0
  get: ^4.6.6
  intl: ^0.18.1
  d_view: ^0.0.5
  d_method: ^0.2.1
  d_input: ^0.1.2
  d_info: ^0.2.2
  d_button: ^0.0.10
  google_fonts: ^4.0.5
  grouped_list: ^5.1.2
  shimmer: ^3.0.0
  # animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
